import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/providers";
import TorchBackground from "@/components/torch-background";
import Nav from "@/components/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Sometype+Mono:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>
          <TorchBackground />
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
